### ISSUE TITLE
How do you deal with errors?

### ISSUE THREAD

**Issue by jeffbski** [kitten/wonka#39]
Looking through the readme, examples, and code, I don't see how to deal with errors whether explicit or whether handled with something like Result. 

Obviously if one of the operators or sources returns an error, then it should short circuit the processing in the pipeline. 

Since promises, observables, and callbags all can have errors, how are they dealt with?

**Comment by kitten** [comment]
When I wrote `wonka` I've debated the pros and cons of having error states in parallel to the stream's completion. There are multiple problems and reasons though why it's not included today.

- When modeling synchronous streams, errors can be thrown and can still shortcircuit execution safely. This is fundamentally the "wrong" way to do it, but saves the library from having to deal with error handling around every function that's passed to operators like `map` or `filter`, instead of blindly trusting those (So this is a very non-Reason/OCaml part of the answer)
- When dealing with asynchronous results, errors are often outcomes of an asynchronous operation and can be modelled as part of the stream's values. This has to do with APIs like `fetch` or other effects that will eventually output results. This can be modelled in userland by having `type resultT('a) = Error(Js.Exn.t) | Ok('a)` or something similar in TS/Ocaml/etc. Hence this is concerned that at times errors are part of values of an asynchronous stream, rather than completion, so shortcircuiting isn't always necessary.
- Once the [`End` signal](https://github.com/kitten/wonka/blob/master/src/wonka_types.re#L36) carries an error, it would be the only "idiomatic" way for the library to carry errors, so the above case would then co-exist with shortcircuiting errors, even though shortcircuited errors are more common in the first, synchronous case.

So all in all, I see this as handling unexpected errors. But the assumption is that unexpected exceptions are meant to be kept in check and not occur in the first place. For all other cases modeling errors as part of the stream's values seems acceptable in my opinion.

It's just heavily tied to the use-cases of Wonka, which aren't the same as other stream libraries. Hope that makes sense so far :)

**Comment by jeffbski** [comment]
I had expected that maybe you were dealing with them in a monadic way, maybe using Result or similar, especially with asynchronous results but it sounds like there's no special handling so every step would need to check the value on their own?

I'm not sure what you mean by unexpected errors, seems like we always hope that things will work as they should, but since we are often working with external systems and changing environments things sometimes fail. 

It doesn't even look like errors from promises or observables would even make it into the stream, so I guess they are just silently dropped? 

I'm not sure I can really envision many use-cases where errors are not possible. Like you said fetch and any I/O can all have errors or fail to respond within an allowed time (generating a timeout error) so one should be able to handle those in an elegant way. 

I guess if wonka isn't going to deal with errors you should probably explain that in the README very clearly. I'd also question whether it is valid to say that you interop with promises and observables since it would only work with those that never generate errors. 

Thanks for taking the time to explain this to me.

**Comment by kitten** [comment]
> It doesn't even look like errors from promises or observables would even make it into the stream, so I guess they are just silently dropped?

Yes, currently there's no `fromPromise` or `fromObservable` helper that automatically wraps things in a result as that'd be placing some assumptions onto each environment, of which wonka supports several. The more expected case here is to wrap any effect that is expected to error using `Wonka.make`, which can then be used to implement cancellation and wrap results in a monadic error wrapper.

> I'm not sure I can really envision many use-cases where errors are not possible. Like you said fetch and any I/O can all have errors or fail to respond within an allowed time (generating a timeout error) so one should be able to handle those in an elegant way.

This library is definitely still very geared towards usage in our GraphQL client, so it depends on how we'd look at it. There we're already wrapping `fetch` (or other transports) so that any result from the Wonka sources would contain errors: https://github.com/FormidableLabs/urql/blob/3329005c70b314be15a348bd7137cf446566c7dd/src/types.ts#L61-L73

> I guess if wonka isn't going to deal with errors you should probably explain that in the README very clearly. I'd also question whether it is valid to say that you interop with promises, observables, and callbags since it would only work with those that never generate errors.

That's a good point :+1: I suppose the longterm solution is though to either provide wrappers that can deal with errors by using something like the `resultT` type in the last comment or something else 🤔 I'll also have to investigate whether it wouldn't be more transparent to extend the `End` event to include errors.

**Comment by jeffbski** [comment]
Thanks. yes, if one needs to wrap with a resultT or use Wonka.make then that would be great to see examples of that and maybe long term having something baked in.

**Comment by ollydixon** [comment]
Can someone please give a small example?

**Comment by mobily** [comment]
@ollydixon here is a little snippet of how I handle errors with `wonka` and `@mobily/ts-belt` ([ts-belt](https://mobily.github.io/ts-belt/docs/) is a library for FP in TS, highly inspired by ReScript’s Belt)

First off, we need to create the source creator that wraps a promise operation result in `Result`, which has the following signature: `type Result<A, B> = Ok<A> | Error<B>`

```ts
import { R, Result } from '@mobily/ts-belt'
import { Source, make } from 'wonka'

class Failure {
  error: Error;

  constructor(error: Error) {
    this.error = error;
  }

  get message() {
    return this.error.message;
  }

  get stack() {
    return this.error.stack;
  }
}

const failwith = (error: Error | string) => {
  if (typeof error === 'string') {
    return new Failure(new Error(error));
  }

  return new Failure(error);
};

const fromPromiseR = <T>(promise: Promise<T>): Source<Result<NonNullable<T>, Failure>> => {
  return make<Result<NonNullable<T>, Failure>>(observer => {
    const { next, complete } = observer
    const isCancelled = {
      current: false,
    }

    promise
      .then(result => {
        if (!isCancelled.current) {
          next(R.fromNullable(failwith('nullable'), result))
          return complete()
        }
      })
      .catch(err => {
        if (!isCancelled.current) {
          next(R.Error(failwith(err)))
          return complete()
        }
      })

    return () => {
      isCancelled.current = true
    }
  })
}
```

and now, we can extract an `Ok` value using `ts-belt` helpers, in this example I'm gonna use `R.getWithDefault`, which returns a value if a result is `Ok`, otherwise, returns a default value.

```ts
import { R } from '@mobily/ts-belt'
import { map, subscribe } from 'wonka'

const fakePromise = <T>(status: 'resolve' | 'reject', value: T) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      status === 'resolve' ? resolve(value) : reject(new Error('oops!'));
    }, 1000);
  });
};
const defaultEmptyArray: number[] = [];

pipe(
  // update 'resolve' to 'reject' to see how it handles errors
  fromPromiseR(fakePromise('resolve', [1, 2, 3])),
  tap((result) => console.log('EXAMPLE #1 – tap:', result)),
  map(R.getWithDefault(defaultEmptyArray)),
  subscribe((list) => {
    console.log('EXAMPLE #1 – subscribe:', list);
  })
);
```

here is the full example: https://stackblitz.com/edit/typescript-sqkail?devtoolsheight=33&file=index.ts

I've been using this approach in several projects and it works pretty well, hopefully, it will be a hint for you on how to tackle this problem :)

**Comment by Javarome** [comment]
Got the same issue and didn't want to convey failure to be checked at each level, so I built a "safe" wrapper that can handle errors and delegate its processing to error handlers (yes, it's not FP so you're gonna hate it, sorry):
```ts
export class SafeOperator {

  readonly errorHandlers: ErrorHandler[]

  constructor(...errorHandlers: ErrorHandler[]) {
    this.errorHandlers = errorHandlers || []
  }

  handleError(e: any) {
    const err = e instanceof Error ? e as Error : new MobkoiError((e as any).toString(), e)
    for (const errorHandler of this.errorHandlers) {
      errorHandler.handle(err)
    }
  }

  wrap(fn: Function) {
    return (...inputs: any) => {
      try {
        return fn(...inputs)
      } catch (e) {
        this.handleError(e)
      }
    }
  }

  onPush = <T>(callback: (value: T) => void): Operator<T, T> => {
    return onPush<T>(this.wrap(callback))
  }

  tap = <T>(callback: (value: T) => void): Operator<T, T> => {
    return this.onPush(callback)
  }

  map = <In, Out>(callback: (value: In) => Out): Operator<In, Out> => {
    return map<In, Out>(this.wrap(callback))
  }

  mergeMap = <In, Out>(callback: (value: In) => Source<Out>): Operator<In, Out> => {
    return mergeMap<In, Out>(this.wrap(callback))
  }

  scan = <In, Out>(callback: (acc: Out, value: In) => Out, seed: Out): Operator<In, Out> => {
    return scan<In, Out>(this.wrap(callback), seed)
  }

  filter<T>(predicate: (value: T) => boolean): Operator<T, T> {
    return filter<T>(this.wrap(predicate))
  };

  subscribe<T>(subscriber: (value: T) => void) {
    return subscribe<T>(this.wrap(subscriber))
  };

  fromPromise<T>(promise: Promise<T>): Source<T> {
    return fromPromise<T>(promise.catch(e => {
      this.handleError(e)
    }).then((x: void | T): any => {
      return x
    }))
  }
}
```
Sample usage:
```ts
 return pipe(
      fromValue(someFunc()),
      safe.mergeMap((item) => handleItem$(item)),
      safe.map((otherItem => mapIt(otherItem))
)
```
You can either use local safe wrappers with local error handlers or/and use a single `safe` instance handling to your app-wide uncatched errors and pass it where you need it.
